version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: host.docker.internal
      PMA_PORT: 3306

volumes:
  db_data: